## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on: pull_request

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Decode TOKEN
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: echo token="$TOKEN" > ./local.properties

      - name: Unit tests
        run: ./gradlew test
  ## 4
  android_tests:
    runs-on: [ macos-latest ]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Decode TOKEN
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: echo token="$TOKEN" > ./local.properties

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
